ci(build.yml): fix armv7 packages' architecture
daeuniverse/daed pull request #145
Opened 2023-07-10 06:10 UTC by MarksonHon

### Background

### Checklist

- [x] The Pull Request has been fully tested
- [ ] There's an entry in the CHANGELOG
- [ ] There is a user-facing docs PR against https://github.com/daeuniverse/daed

### Full changelog

- [Implement ...]

### Issue reference

Fix #_[issue number]_

2023-07-10 06:11 UTC, MarksonHon commented
DON'T merge this pull request until fpm fix [pacman's build bug](https://github.com/jordansissel/fpm/pull/2017)

2023-07-10 06:18 UTC, kunish commented
OK, noted, we can mark this PR as DRAFT for now to be extra safe

2023-07-10 10:51 UTC, yqlbu submitted a review, later dismissed

2023-07-11 17:45 UTC, kunish commented on .github/workflows/build.yml
>              sudo gem install fpm -v 1.15.1
Note: dont forget to update fpm when the new release gets published

2023-07-15 03:55 UTC, MarksonHon commented
Finished those jobs:
1. Fix armv7 packages' architectures, it should be `armhf` in Debian, `arm7hf` in Arch Linux ARM and `armhfp` in RPM.
2. Arch Linux ARM and RPM use `aarch64` for `arm64` architecture, while Debian use `arm64`.
3. Don't build MIPS family's pacman package for Arch Linux MIPS port has died for 10 years.
This PR can be merged now

2023-07-15 03:58 UTC, kunish commented
@yqlbu instantiate-check-runs is causing PR build failure, please help

2023-07-15 04:06 UTC, yqlbu commented
@kunish Sure, let me take a closer look

2023-07-15 04:16 UTC, yqlbu commented
> @yqlbu instantiate-check-runs is causing PR build failure, please help

The root cause is that the `feature-branch` is outside of `daeuniverse`. For now, it is hard to fix. As a temporary solution, @MarksonHon please push your local branch branch to `origin daeuniverse` followed by the commands below:

```bash
git remote add upstream https://github.com/daeuniverse/daed
git fetch upstream --prune
git push -u upstream <your feature branch name>
```

2023-07-15 09:08 UTC, yqlbu commented
> > @yqlbu instantiate-check-runs is causing PR build failure, please help
> 
> The root cause is that the `feature-branch` is outside of `daeuniverse`. For now, it is hard to fix. As a temporary solution, @MarksonHon please push your local branch branch to `origin daeuniverse` followed by the commands below:
> 
> ```shell
> git remote add upstream https://github.com/daeuniverse/daed
> git fetch upstream --prune
> git push -u upstream <your feature branch name>
> ```

Issue was resolved in #167

2023-07-16 04:21 UTC, kunish requested changes

2023-07-16 04:21 UTC, kunish commented on .github/workflows/build.yml
> +        if: ${{ env.GOARM != '5' && env.GOARM != '6' && env.GOARCH != 'mips' && env.GOARCH != 'mipsle' && env.GOARCH != 'mips64' && env.GOARCH != 'mips64le' }}
```suggestion
        if: !contains(fromJSON('["5", "6"]'), env.GOARM) && !contains(fromJSON('["mips", "mipsle", "mips64", "mips64le"]'), env.GOARCH)
```

2023-07-16 05:18 UTC, MarksonHon commented
> I think we also need to update [pr-build.yml](https://github.com/daeuniverse/daed/blob/main/.github/workflows/pr-build.yml), [release.yml](https://github.com/daeuniverse/daed/blob/main/.github/workflows/release.yml), and [prerelease](https://github.com/daeuniverse/daed/blob/main/.github/workflows/prerelease.yml)

`pr-build.yml` has no package build flow, sync to `release.yml` and `prerelease.yml`

2023-07-16 05:50 UTC, kunish reviewed
It's too complicated for me to really have a good understanding what this PR is doing, can you leave a brief explanation to help people like me?

2023-07-16 05:57 UTC, MarksonHon commented
> It's too complicated for me to really have a good understanding what this PR is doing, can you leave a brief explanation to help people like me?

https://github.com/daeuniverse/daed/pull/145#issuecomment-1636646309

Some packages built by Action cannot be installed on target operating system, such as Arch Linux ARM64, Debian armv7, this PR is coming for fixing this problem

2023-07-16 06:00 UTC, kunish approved these changes

2023-07-16 06:30 UTC, merged