ci(docker): rework workflow (3rd time)
daeuniverse/daed pull request #289
Opened 2023-09-21 16:30 UTC by hero-intelligent

### Background

Thanks for your patience. Maybe this will help. Only the tested will be squashed into one commit and pushed here. I'll try not to close pr so frequently. Feel free to review my working status in my repo. 

### Checklist

- [X] The Pull Request has been fully tested
- [ ] There's an entry in the CHANGELOGS
- [ ] There is a user-facing docs PR against https://github.com/daeuniverse/daed

### Full Changelogs

- ci(docker): docker build once and push to multiple repos
- ci(docker): docker build and push with tags
- ci(docker): come back arm64 platform support (Experimental)
- ci(docker): publish dockerhub image
- ci(docker): action version upgrade
- ci(docker): multiple action trigger
- ci(docker): build with tag on dashboard
- ci(docker): i386, armv7 armv8 platform support (Experimental)

### Issue Reference

https://github.com/daeuniverse/daed/issues/280
https://github.com/daeuniverse/daed/pull/267
https://github.com/daeuniverse/daed/pull/286

### Test Result

[Action page](https://github.com/hero-intelligent/daed/actions/runs/6247355789/job/16959768528)
[Dockerhub page](https://hub.docker.com/r/huangqizigailee/daed-test-test/tags)
[Download log archive](https://github.com/hero-intelligent/daed/suites/16364107338/logs?attempt=1)
[View raw logs](https://github.com/hero-intelligent/daed/commit/37a2ba27e8ff6601f36314fb90781399332d1f2e/checks/16959768528/logs)

It should work, but we need cooperation.

2023-10-19 15:34 UTC, yqlbu commented
@hero-intelligent When it comes to `build candidates`, I think we ONLY need to take the following architectures into consideration:

- amd64
- arm64

2023-10-19 15:41 UTC, yqlbu requested changes

2023-10-19 15:41 UTC, yqlbu commented on publish.Dockerfile
> +FROM golang:1.21-bookworm as build-bundle-directly-for-web--has-been-built-from-outside-of-dokerfile
```suggestion
FROM golang:1.21-bookworm as base
```

2023-10-19 15:41 UTC, yqlbu commented on publish.Dockerfile
> +# RUN git clone --recursive https://github.com/daeuniverse/dae-wing.git wing
```suggestion
```

2023-10-19 15:41 UTC, yqlbu commented on publish.Dockerfile
> +FROM alpine as this-image-is-built-for-final-publish-with-support-of-multiple-platforms
```suggestion
FROM alpine as prod
```

2023-10-19 15:41 UTC, yqlbu commented on publish.Dockerfile
> +ARG DAED_VERSION=self-build
```suggestion
ARG DAED_VERSION
```

2023-10-19 15:41 UTC, yqlbu commented on publish.Dockerfile
> +
```suggestion
ARG DAED_VERSION
```

We pass the version from CI as `build-arg`

2023-10-19 15:49 UTC, yqlbu commented
From your sample workflow run, everything meets our expectations except the list of build candidates (platforms). Ideally, we should ONLY consider offering this containerization deployment alternative to `amd64` and `arm64` users and ignoring all other unnecessary platforms given the consideration of less common adoption of other platforms such as `ppc64le`.

2023-10-20 08:30 UTC, kunish requested changes

2023-10-20 08:30 UTC, kunish commented on .github/workflows/publish-docker-image.yml
> +  REGISTRY_IMAGE: daeuniverse/daed
This variable is no longer necessary

2023-10-20 08:30 UTC, kunish commented on .github/workflows/publish-docker-image.yml
> +        #   submodules: 'recursive'
We did it on purpose, as those source code files under submodules are also used by linux distro packages, such as archlinux and gentoo. For example, the packaging process of gentoo is done inside a isolated environment, which means we can't do git clone as we desire.

2023-10-20 08:46 UTC, hero-intelligent commented on .github/workflows/publish-docker-image.yml
> +        #   submodules: 'recursive'
Oh, does build-web need sub-modules as well? I thought this process just renders htmls.

2023-10-20 08:47 UTC, kunish commented on .github/workflows/publish-docker-image.yml
> +        #   submodules: 'recursive'
Yeah, they are requested by package maintainers

2023-10-20 09:09 UTC, kunish approved these changes

2023-10-20 09:09 UTC, merged

2023-10-20 09:10 UTC, kunish commented
Awesome, let's ship it!

2023-10-20 09:39 UTC, kunish commented
> This build process is time consuming, which takes about one hour. You can disable `on push` after this run time if you don't need to build after every single update.

OK

2023-10-20 10:05 UTC, yqlbu commented
@hero-intelligent I will update the workflow definition accordingly. Stay tuned.